DROP TABLE PERSON;
DROP TABLE JOB;

CREATE TABLE JOB(
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE SEQ_PERSON
    MAXVALUE 99999
    MINVALUE 1
    NOCYCLE 
    NOCACHE;
    
CREATE TABLE PERSON(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
);
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '엠씨');

INSERT INTO PERSON VALUES (SEQ_PERSON.NEXTVAL, '정우성', (SELECT JNO FROM JOB WHERE JNAME = '배우'), 90, 80, 81); --1
SELECT NAME||'('||NO||'번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON P, JOB J
    WHERE P.JNO = J.JNO AND JNAME = '배우'
    ORDER BY SUM DESC;--2
SELECT ROWNUM RANK, S.*FROM(SELECT NAME||'('||NO||'번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON P, JOB J
                                WHERE P.JNO = J.JNO AND JNAME = '배우'
                                ORDER BY SUM DESC) S;--2
SELECT ROWNUM RANK, S.*FROM(SELECT NAME||'('||NO||'번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON P, JOB J
                                WHERE P.JNO = J.JNO 
                                ORDER BY SUM DESC) S;--3
SELECT * FROM JOB;
SELECT * FROM PERSON;

SELECT JNAME FROM JOB;
COMMIT;