--[10] VIEW TOP N
--1. VIEW: 일부의 필드 및 행만 사용하기 위한 가상의 테이블
--(1) 단순 뷰 
CREATE OR REPLACE VIEW EMPV0 --일부 필드를 갖는 가상의 테이블
    AS SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP;
SELECT * FROM EMPV0;--일부만 접근 가능
INSERT INTO EMPV0 VALUES (1111, 'JIM', 'IT', 40); --EMP 테이블에 추가됨, 나머지는 NULL로 추가
UPDATE EMPV0 SET JOB = 'ANALYST' WHERE EMPNO = 1111;

CREATE OR REPLACE VIEW EMPV0 --30번 부서행만
    AS SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMPV0;
SELECT * FROM USER_VIEWS; --데이터 딕셔너리 뷰
INSERT INTO EMPV0 VALUES (1113, 'SIM', NULL, NULL, NULL, NULL, NULL, 30 );
INSERT INTO EMPV0 VALUES (1112, 'TIM', NULL, NULL, NULL, NULL, NULL, 40 );--삽입은 되나 뷰에서는 표기되지 않음
DELETE FROM EMP WHERE EMPNO <= 1113;
COMMIT;
--예외시 오류 처리
CREATE OR REPLACE VIEW EMPV0
    AS SELECT * FROM EMP WHERE DEPTNO = 30
    WITH CHECK OPTION; --제한 조건
INSERT INTO EMPV0 VALUES (1111, 'TIM', NULL, NULL, NULL, NULL, NULL, 30 );
INSERT INTO EMPV0 VALUES (1112, 'RIM', NULL, NULL, NULL, NULL, NULL, 40 );--오류 처리
DELETE FROM EMPV0 WHERE EMPNO = 1111;

--(2) 복합뷰
CREATE OR REPLACE VIEW EMPV1
    AS SELECT EMPNO, ENAME, JOB, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
SELECT * FROM EMPV1;--복합뷰는 삽입이 불가능(두개 이상의 테이블 사용)
CREATE OR REPLACE VIEW EMPV2
    AS SELECT EMPNO, ENAME, DEPTNO FROM EMP
    WITH READ ONLY; --읽기 전용 VIEW
SELECT EMPNO, ENAME, DNAME FROM EMPV2 E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO; --VIEW와 조인 가능, 삽입 불가능
CREATE OR REPLACE VIEW EMPV3
    AS SELECT ENAME, SAL FROM EMP;
INSERT INTO EMPV3 VALUES ('TIM', 300 );
--PRIMARY KEY가 VIEW에 포함되지 않아 NULL로 들어가는 경우 삽입 불가능
CREATE OR REPLACE VIEW EMPV3
    AS SELECT EMPNO, ENAME, SAL FROM EMP; --WHERE절 없이 제한 조건 불가능
CREATE OR REPLACE VIEW EMPV4
    AS SELECT EMPNO, ENAME, SAL*12 ANNUAL FROM EMP; -- ALIAS 없이 VIEW 생성 불가능, 따로 ALIAS 주는 경우 모든 필드에 줘야함
--삽입시 EMP에 들어가기 때문에 함수값 삽입 불가능

--부서번호, 최소급여, 최대급여, 부서평균급여
CREATE OR REPLACE VIEW DEPTV1
    AS SELECT DEPTNO, MIN(SAL) MIN, MAX(SAL) MAX, ROUND(AVG(SAL)) AVG FROM EMP GROUP BY DEPTNO;
SELECT * FROM DEPTV1;
SELECT DEPT.DEPTNO, DNAME, MIN, MAX, AVG FROM DEPTV1, DEPT
    WHERE DEPT.DEPTNO = DEPTV1.DEPTNO;
--중복 제거 뷰
SELECT DISTINCT JOB, DEPTNO FROM EMP ORDER BY JOB; --SUB
CREATE OR REPLACE VIEW EMPV5
    AS SELECT DISTINCT JOB, DEPTNO FROM EMP ORDER BY JOB;
SELECT * FROM EMPV5;

--2. INLINE VIEW : SQL문 수행하는 한줄의 명령어에서만 유용한 뷰
SELECT AVG(SAL) FROM (SELECT SAL FROM EMP WHERE SAL > 2000); --서브쿼리 테이블
--INLINE VIEW
SELECT ENAME, SAL, DEPTNO FROM EMP;--1
SELECT DEPTNO, ROUND(AVG(SAL)) AVG FROM EMP GROUP BY DEPTNO;--2
SELECT ENAME, SAL, E.DEPTNO, S.AVG  FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL)) AVG FROM EMP GROUP BY DEPTNO) S
    WHERE ENAME = 'SMITH' AND E.DEPTNO = S.DEPTNO; 
SELECT ENAME, SAL, E.DEPTNO, S.AVG  FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL)) AVG FROM EMP GROUP BY DEPTNO) S
    WHERE SAL > S.AVG AND E.DEPTNO = S.DEPTNO; 
    
--TOP-N(1~10위까지)
SELECT ROWNUM, ENAME, SAL FROM EMP WHERE DEPTNO = 30;-- 테이블에서 행의 논리적인 순서
SELECT ROWNUM, ENAME, SAL FROM EMP ORDER BY SAL;
SELECT ROWNUM, ENAME, SAL FROM (SELECT * FROM EMP ORDER BY SAL)--순서대로 나열된 뷰 생성
    WHERE ROWNUM < 6;
SELECT RANK() OVER (ORDER BY SAL) RANK, 
    DENSE_RANK() OVER (ORDER BY SAL) D_RANK,
    ROW_NUMBER() OVER (ORDER BY SAL) N_RANK,
    ENAME, SAL
    FROM EMP;
--TOP-N구문
SELECT ROWNUM "RANK", ENAME, SAL FROM (SELECT * FROM EMP ORDER BY SAL);
SELECT RN, ENAME, SAL FROM (SELECT ROWNUM RN, ENAME, SAL FROM (SELECT * FROM EMP ORDER BY SAL )) --셋팅 후 가지고 온 뒤에 뽑아냄
    WHERE RN BETWEEN 6 AND 10;
SELECT RN, EMPNO, ENAME, JOB, MGR, HIREDATE FROM (SELECT ROWNUM RN, EMPNO, ENAME, JOB, MGR, HIREDATE FROM (SELECT * FROM EMP ORDER BY ENAME ))
    WHERE RN BETWEEN 6 AND 10;
    
--ex)
-- 1. 부서명과 사원명을 출력하는 용도의 뷰, DNAME_ENAME_VU 를 작성하시오
CREATE OR REPLACE VIEW DNAME_ENAME_VU 
    AS SELECT DNAME, ENAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
-- 2. 사원명과 직속상관명을 출력하는 용도의 뷰,  WORKER_MANAGER_VU를 작성하시오
CREATE OR REPLACE VIEW WORKER_MANAGER_VU 
    AS SELECT W.ENAME WORKER, M.ENAME BOSS FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO;--ALIAS 필요
-- 3. 부서별 급여합계 등수를 출력하시오(부서번호, 급여합계, 등수) ? 친구출제
SELECT DEPTNO, SUM, ROWNUM RN FROM (SELECT DEPTNO, SUM(SAL) SUM FROM EMP GROUP BY DEPTNO ORDER BY SUM(SAL));
-- 3-1. 부서별 급여합계 등수가 2~3등인 부서번호, 급여합계, 등수를 출력하시오.
SELECT DEPTNO, SUM, RN FROM (SELECT DEPTNO, SUM, ROWNUM RN FROM (SELECT DEPTNO, SUM(SAL) SUM FROM EMP GROUP BY DEPTNO ORDER BY SUM(SAL)))
    WHERE RN BETWEEN 2 AND 3;
-- 4. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 순으로 정렬하시오
SELECT ROWNUM RN, EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC;
-- 5. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 5명을 출력하시오
SELECT EMPNO, ENAME, HIREDATE FROM (SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC )
    WHERE ROWNUM <= 5;
-- 6. 사원 테이블에서 사번, 사원명, 입사일을 최신부터 오래된 순으로 6번째로 늦은 사원부터 10번째 사원까지 
SELECT RN, EMPNO, ENAME, HIREDATE FROM (SELECT ROWNUM RN, EMPNO, ENAME, HIREDATE FROM (SELECT * FROM EMP ORDER BY HIREDATE DESC ))
    WHERE RN BETWEEN 6 AND 10;