--[12] TRANSACTION
COMMIT;--트랜잭션 비워짐
SELECT * FROM DEPT01;
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
DELETE FROM DEPT01;
ROLLBACK; --복귀

DELETE FROM DEPT01 WHERE DEPTNO = 40;--40번 삭제
SELECT * FROM DEPT01;
COMMIT;

DELETE FROM DEPT01 WHERE DEPTNO = 30;
SELECT * FROM DEPT01;
SAVEPOINT C1;--10, 20번 부서 존재
DELETE FROM DEPT01 WHERE DEPTNO = 20;
SELECT * FROM DEPT01;
SAVEPOINT C2;--10번 부서 존재
DELETE FROM DEPT01 WHERE DEPTNO = 10;
SELECT * FROM DEPT01;
SAVEPOINT C3;
ROLLBACK TO C1;
SELECT * FROM DEPT01;
COMMIT;