--[3] JOIN: 테이블 2개 이상 연결하여 검색

SELECT * FROM EMP 
    WHERE ENAME = 'SCOTT'; --부서번호 DEPTNO:20
SELECT * FROM DEPT;--두번의 연산 필요

--CROSS JOIN(FROM절에 테이블 2개 이상, N*M)
SELECT * FROM EMP,DEPT 
    WHERE ENAME = 'SCOTT';
    
--EQUI JOIN(같은 값만 JOIN)
SELECT * FROM EMP,DEPT 
    WHERE ENAME = 'SCOTT' AND EMP.DEPTNO = DEPT.DEPTNO;
SELECT * FROM EMP,DEPT 
    WHERE EMP.DEPTNO = DEPT.DEPTNO;
--이름, 부서명, 부서번호
SELECT ENAME, DNAME, E.DEPTNO FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO; --테이블의 ALIAS는 무조건 사용, 중복되지 않는 요소는 테이블명 생략 
SELECT E.*, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO;
SELECT EMPNO, ENAME, E.DEPTNO, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO;
SELECT ENAME, JOB, SAL, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND SAL>=2000;
SELECT ENAME, JOB, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND LOC = 'CHICAGO';
SELECT ENAME, JOB, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO IN (10,20) 
    ORDER BY SAL;
SELECT ENAME, SAL, COMM, SAL*12+NVL(COMM,0) ANNUAL, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO;
SELECT ENAME, SAL, COMM, SAL*12+NVL(COMM,0) ANNUAL, DNAME, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND JOB IN ('SALESMAN','MANAGER') 
    ORDER BY ANNUAL DESC;
SELECT ENAME, SAL, HIREDATE, D.DEPTNO, DNAME FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND COMM IS NULL AND SAL>=1200 
    ORDER BY DNAME, SAL DESC;
--EX)
--뉴욕에서 근무하는 사원의 이름과 급여를 출력하시오
SELECT ENAME, SAL FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND LOC = 'NEW YORK';
--ACCOUNTING 부서 소속 사원의 이름과 입사일을 출력하시오
SELECT ENAME,HIREDATE FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND DNAME = 'ACCOUNTING';
--직급이 MANAGER인 사원의 이름, 부서명을 출력하시오
SELECT ENAME, DNAME FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND JOB = 'MANAGER';
--Comm이 null이 아닌 사원의 이름, 급여, 부서코드, 근무지를 출력하시오.
SELECT ENAME, SAL, D.DEPTNO, LOC FROM EMP E,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND COMM IS NOT NULL;
--NON-EQUI JOIN (비교 연산자 이용)
SELECT ENAME, SAL FROM EMP 
    WHERE ENAME = 'SCOTT';
SELECT * FROM SALGRADE;
SELECT ENAME, SAL, GRADE, LOSAL, HISAL FROM EMP, SALGRADE 
    WHERE ENAME = 'SCOTT' AND SAL BETWEEN LOSAL AND HISAL;--ALIAS하지 않음
SELECT EMPNO, ENAME, JOB, MGR, SAL, GRADE||'급' "급여등급" FROM EMP, SALGRADE 
    WHERE SAL BETWEEN LOSAL AND HISAL;
--ex2)
--Comm이 null이 아닌 사원의 이름, 급여, 등급, 부서번호, 부서이름, 근무지를 출력하시오.
SELECT ENAME, SAL, GRADE, E.DEPTNO, DNAME, LOC  FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;
--이름, 급여, 입사일, 급여등급
SELECT ENAME, SAL, HIREDATE, GRADE FROM EMP, SALGRADE 
    WHERE SAL BETWEEN LOSAL AND HISAL;
--이름, 급여, 입사일, 급여등급, 부서명, 근무지
SELECT ENAME, SAL, HIREDATE, GRADE, DNAME, LOC  FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL;
--이름, 급여, 등급, 부서코드, 근무지. 단 comm 이 null아닌 경우
SELECT ENAME, SAL, GRADE, E.DEPTNO, LOC  FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;
--이름, 급여, 급여등급, 연봉, 부서명, 부서별 출력, 부서가 같으면 연봉순. 연봉=(sal+comm)*12 comm이 null이면 0
SELECT ENAME, SAL, GRADE, (SAL+NVL(COMM,0))*12, DNAME FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL 
    ORDER BY DNAME,(SAL+NVL(COMM,0))*12;
--이름, 업무, 급여, 등급, 부서코드, 부서명 출력. 급여가 1000~3000사이. 정렬조건 : 부서별, 부서같으면 업무별, 업무같으면 급여 큰순
SELECT ENAME, SAL, GRADE, E.DEPTNO, DNAME  FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND SAL BETWEEN 1000 AND 3000
    ORDER BY DNAME, JOB, SAL DESC;
--이름, 급여, 등급, 입사일, 근무지. 81년에 입사한 사람. 등급 큰순
SELECT ENAME, SAL, GRADE, HIREDATE, LOC  FROM EMP E,DEPT D, SALGRADE 
    WHERE E.DEPTNO = D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND HIREDATE LIKE '81/%'
    ORDER BY GRADE DESC;
    
---SELF JOIN(하나의 테이블 내에서 조인)
SELECT W.EMPNO, W.ENAME, W.MGR, M.ENAME FROM EMP W, EMP M
    WHERE W.ENAME = 'SMITH' AND W.MGR = M.EMPNO; --셀프 조인
SELECT W.EMPNO, W.ENAME, W.MGR, M.ENAME FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO;
--ex3)
SELECT W.ENAME||'의 상사는 '||M.ENAME||'다.' LIST FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO;
SELECT W.ENAME, W.JOB FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO AND M.ENAME = 'KING';
SELECT W.ENAME, M.ENAME FROM EMP W, EMP M
    WHERE W.DEPTNO = M.DEPTNO AND W.ENAME = 'SCOTT' AND M.ENAME != 'SCOTT';
--SELF JOIN에 두 개의 EQUI JOIN TABLE 병합
SELECT E1.ENAME, D1.LOC FROM EMP E1, DEPT D1
    WHERE E1.DEPTNO = D1.DEPTNO
    AND E1.ENAME = 'SCOTT'; 
SELECT E2.ENAME, D2.LOC FROM EMP E2, DEPT D2
    WHERE E2.DEPTNO = D2.DEPTNO
    AND E2.ENAME = 'SCOTT'; 
SELECT E1.ENAME, D1.LOC, E2.ENAME, D2.LOC FROM EMP E1, DEPT D1, EMP E2, DEPT D2
    WHERE E1.DEPTNO = D1.DEPTNO AND E2.DEPTNO = D2.DEPTNO 
    AND D1.LOC = D2.LOC AND E1.ENAME = 'SCOTT' AND E2.ENAME != 'SCOTT';
    
--OUTER JOIN(조건에 만족하지 않는 행까지 출력, 외부 조인)
SELECT W.EMPNO, W.ENAME, NVL(W.MGR, 0), NVL(M.ENAME, 'CEO') FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO(+);--조건에 충족되지 않은 행 출력 > CEO출력
SELECT W.EMPNO, W.ENAME, NVL(W.MGR, 0), NVL(M.ENAME, 'CEO') FROM EMP W, EMP M
    WHERE W.MGR(+) = M.EMPNO AND W.EMPNO IS NULL; --말단 사원 출력
SELECT E.*, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO(+) = D.DEPTNO;-- 14행과 4행 > 40번이 나오지 않음 > 안 나오는 쪽에 (+)
SELECT W.ENAME||'의 상사는 '||NVL(M.ENAME, '無')||'입니다.' LIST FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO(+);

--EX JOIN)
--PART1
--1. 이름, 직속상사
SELECT W.ENAME, M.ENAME FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO;
--2. 이름, 급여, 업무, 직속상사
SELECT W.ENAME, W.SAL, W.JOB, M.ENAME FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO;
--3. 이름, 급여, 업무, 직속상사. (상사가 없는 직원까지 전체 직원 다 출력.
    --상사가 없을 시 '없음'으로 출력)
SELECT W.ENAME, W.SAL, W.JOB, NVL(M.ENAME, '없음') FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO(+);
--4. 이름, 급여, 부서명, 직속상사명
SELECT W.ENAME, W.SAL, DNAME, M.ENAME FROM EMP W, EMP M, DEPT D
    WHERE W.MGR = M.EMPNO AND W.DEPTNO = D.DEPTNO;
--5. 이름, 급여, 부서코드, 부서명, 근무지, 직속상사명, (상사가 없는 직원까지 전체 직원 다 출력)
SELECT W.ENAME, W.SAL, W.DEPTNO, DNAME, D.LOC, M.ENAME FROM EMP W, EMP M, DEPT D
    WHERE W.MGR = M.EMPNO(+) AND W.DEPTNO = D.DEPTNO;
--6. 이름, 급여, 등급, 부서명, 직속상사명. 급여가 2000이상인 사람
SELECT W.ENAME, W.SAL, S.GRADE, D.DNAME, M.ENAME FROM EMP W, EMP M, DEPT D, SALGRADE S
    WHERE W.DEPTNO = D.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL AND W.SAL >=2000 AND W.MGR = M.EMPNO;
--7. 이름, 급여, 등급, 부서명, 직속상사명, (직속상사가 없는 직원까지 전체직원 부서명 순 정렬)
SELECT W.ENAME, W.SAL, S.GRADE, D.DNAME, M.ENAME FROM EMP W, EMP M, DEPT D, SALGRADE S
    WHERE W.DEPTNO = D.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL AND W.MGR = M.EMPNO(+)
    ORDER BY DNAME;
--8. 이름, 급여, 등급, 부서명, 연봉, 직속상사명. 연봉=(급여+comm)*12 단 comm이 null이면 0
SELECT W.ENAME, W.SAL, S.GRADE, D.DNAME, M.ENAME, (W.SAL+NVL(W.COMM,0)*12) FROM EMP W, EMP M, DEPT D, SALGRADE S
    WHERE W.DEPTNO = D.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL AND W.MGR = M.EMPNO;
--9. 8번을 부서명 순 부서가 같으면 급여가 큰 순 정렬
SELECT W.ENAME, W.SAL, S.GRADE, D.DNAME, M.ENAME, (W.SAL+NVL(W.COMM,0)*12) FROM EMP W, EMP M, DEPT D, SALGRADE S
    WHERE W.DEPTNO = D.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL AND W.MGR = M.EMPNO
    ORDER BY DNAME, W.SAL;
--  PART2
--1.EMP 테이블에서 모든 사원에 대한 이름,부서번호,부서명을 출력하는 SELECT 문장을 작성하여라.
SELECT ENAME, E.DEPTNO, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
--2. EMP 테이블에서 NEW YORK에서 근무하고 있는 사원에 대하여 이름,업무,급여,부서명을 출력
SELECT ENAME, JOB, SAL, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND LOC = 'NEW YORK';
--3. EMP 테이블에서 보너스를 받는 사원에 대하여 이름,부서명,위치를 출력
SELECT ENAME, DNAME, LOC FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND COMM IS NOT NULL AND COMM != 0;
--4. EMP 테이블에서 이름 중 L자가 있는 사원에 대하여 이름,업무,부서명,위치를 출력
SELECT ENAME, JOB, DNAME, LOC FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND ENAME LIKE '%L%';
--5. 사번, 사원명, 부서코드, 부서명을 검색하라. 사원명기준으로 오름차순정열
SELECT EMPNO, ENAME, E.DEPTNO, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY ENAME;
--6. 사번, 사원명, 급여, 부서명을 검색하라. 
    --단 급여가 2000이상인 사원에 대하여 급여를 기준으로 내림차순으로 정열하시오
SELECT EMPNO, ENAME, SAL, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY SAL DESC;
--7. 사번, 사원명, 업무, 급여, 부서명을 검색하시오. 단 업무가 MANAGER이며 급여가 2500이상인
-- 사원에 대하여 사번을 기준으로 오름차순으로 정열하시오.
SELECT EMPNO, ENAME, JOB, DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND JOB = 'MANAGER' AND SAL>=2500
    ORDER BY EMPNO;
--8. 사번, 사원명, 업무, 급여, 등급을 검색하시오. 단, 급여기준 내림차순으로 정렬하시오
SELECT EMPNO, ENAME, JOB, SAL, GRADE FROM EMP, SALGRADE 
    WHERE SAL BETWEEN LOSAL AND HISAL
    ORDER BY SAL DESC;
--9. 사원테이블에서 사원명, 사원의 상사를 검색하시오(상사가 없는 직원까지 전체)
SELECT W.ENAME, NVL(M.ENAME, '없음') FROM EMP W, EMP M
    WHERE W.MGR = M.EMPNO(+);
--10. 사원명, 상사명, 상사의 상사명을 검색하시오
SELECT W.ENAME, M.ENAME, B.ENAME FROM EMP W, EMP M, EMP B
    WHERE W.MGR = M.EMPNO AND M.MGR = B.EMPNO;
--11. 위의 결과에서 상위 상사가 없는 모든 직원의 이름도 출력되도록 수정하시오
SELECT W.ENAME FROM EMP W, EMP M, EMP B
    WHERE W.MGR = M.EMPNO AND M.MGR = B.EMPNO(+) AND B.ENAME IS NULL;