--[4] 단일행 함수
--함수 = 단일행함수 + 그룹함수
SELECT ENAME, TO_CHAR(HIREDATE, 'YYYY"년"MM"월"DD"일"') 입사일 FROM EMP;
SELECT ENAME, INITCAP(ENAME) FROM EMP;--단일행 함수
SELECT SUM(SAL) FROM EMP; --그룹함수(다중행의 결과)
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO; --그룹별 급여 합
--숫자, 문자, 날짜, 형변환, NVL 함수, etc
--(1)숫자 함수
DESC DUAL; --오라클에서 제공하는 1행 1열짜리 범위 테이블
SELECT ABS(-9) FROM DUAL;--절대값
SELECT FLOOR(34.5678) FROM DUAL;--내림
SELECT TRUNC(34.5678, 1) FROM DUAL;--소수점 한자리에서 내림
SELECT TRUNC(34.5678, -1) FROM DUAL;--일의 자리에서 내림
SELECT ENAME, TRUNC(SAL,-1) FROM EMP;
SELECT ROUND(34.5678) FROM DUAL;--소수점에서 반올림
SELECT ROUND(34.5678, 1) FROM DUAL;--소수점 한자리에서 반올림
SELECT ROUND(34.5678, -1) FROM DUAL;--일의 자리에서 반올림
SELECT 10/4 FROM DUAL;--JAVA와 다르게 결과값 계산
SELECT MOD(9,2) FROM DUAL; --나머지 연산자
SELECT MOD('9',2) FROM DUAL;--자동적으로 연산
SELECT * FROM EMP WHERE MOD(TO_CHAR(HIREDATE, 'MM'),2) = 1;

--(2)문자 함수
SELECT UPPER('asdfgh') FROM DUAL;
SELECT LOWER('ASDFGH') FROM DUAL;
SELECT INITCAP('asdfgh') FROM DUAL;
SELECT * FROM EMP WHERE UPPER(JOB) = 'MANAGER';
SELECT EMPNO, INITCAP(ENAME) FROM EMP;
SELECT CONCAT('ASD', 'FGH') FROM DUAL;
SELECT SUBSTR('BONJOUR', 1, 3) FROM DUAL;
SELECT SUBSTRB('오라클', 1, 6) FROM DUAL;--한글이 3바이트
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 4, 2) = '09';
SELECT SUBSTR('010-9999-9999', -4, 4) FROM DUAL;--음수는 뒤부터
SELECT LENGTH('ABCD') FROM DUAL;--문자 갯수
SELECT LENGTHB('ABCD') FROM DUAL;--문자 바이트 수
SELECT LENGTHB('오라클') FROM DUAL;--문자 바이트 수
SELECT INSTR('ABCDEF', 'B') FROM DUAL;--문자의 인덱스 위치
SELECT INSTR('ABCDEFB', 'B', 4) FROM DUAL;--시작위치에서 문자의 인덱스 위치
SELECT * FROM EMP WHERE INSTR(HIREDATE, '09') = 4;
SELECT LPAD('ORACLE', 20, '#') FROM DUAL;--문자를 자리수만큼 확보하고 빈자리엔 문자 채움
SELECT TRIM('      ORACLE             ') FROM DUAL;--좌우 여백 제거
--ex)
SELECT EMPNO, RPAD(SUBSTR(ENAME,1,1), LENGTH(ENAME),'*' ), RPAD(SUBSTR(HIREDATE,1,6), LENGTH(HIREDATE),'*' ) FROM EMP;
SELECT ENAME FROM EMP WHERE INSTR(ENAME, 'R') = 3;
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,3,1) = 'R';
SELECT ENAME FROM EMP WHERE ENAME LIKE '__R%';

--(3)날짜 함수
SELECT SYSDATE FROM DUAL;--현재 날짜, 산술 연산시 일 계산
SELECT ENAME, TRUNC(SYSDATE-HIREDATE) FROM EMP;--근무일수
SELECT ENAME, TRUNC((SYSDATE-HIREDATE)/7) FROM EMP;--근무주수
SELECT ENAME, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) FROM EMP;--근무월수
SELECT ENAME, TRUNC((SYSDATE-HIREDATE)/365) FROM EMP;--근무연수
--ADD_MONTHS(특정날짜, 개월수)
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 6) FROM EMP;--수습기간종료
--NEXT_DAY(특정날짜, 요일)
SELECT NEXT_DAY(SYSDATE, '수') FROM DUAL;
--LAST_DAY(특정날짜)
SELECT LAST_DAY(SYSDATE) FROM DUAL;
--ROUND: 날짜 반올림
SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;--연 반올림 1월 1일
SELECT ROUND(SYSDATE-30, 'MONTH') FROM DUAL;--월 반올림 1일
SELECT ROUND(SYSDATE, 'DAY') FROM DUAL;--요일 반올림 일요일
SELECT ROUND(SYSDATE) FROM DUAL;--일 반올림 0시

SELECT ENAME, HIREDATE, TRUNC(HIREDATE, 'MONTH') FROM EMP;
SELECT ENAME, HIREDATE, ROUND(HIREDATE-9, 'MONTH')+24 FROM EMP;
SELECT ENAME, HIREDATE, SAL, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))*SAL FROM EMP;
SELECT ENAME, HIREDATE, SAL, NVL(COMM,0), TRUNC((SYSDATE-HIREDATE)/365)*(SAL*12+NVL(COMM,0)) FROM EMP;
