--[9] SEQUENCE: 순차번호 생성기, 인위적인 PRIMARY KEY 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1--1부터 시작
    INCREMENT BY 1--1씩 증가
    
    MAXVALUE 9999--마지막 인덱스
    MINVALUE 1--첫 인덱스
    NOCYCLE --순환 없음
    NOCACHE;--캐쉬 없음

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE,--중복 불가
    TEL VARCHAR2(20),
    LAST_MODIFIED DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NUM, NAME, PHONE) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999');--시퀀스 자동 생성
INSERT INTO FRIEND (NUM, NAME, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '김길동', '02-716-1006');    
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-8888', '02-716-1006');
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;--현재 시퀀스

