DROP TABLE BUYITEM;
DROP TABLE WISHLIST;
DROP TABLE BUYCUSTOMER;
DROP TABLE ITEM;
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    ID VARCHAR2(30) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    CADDRESS VARCHAR2(100) UNIQUE,
    CTEL VARCHAR2(20) UNIQUE NOT NULL
);
SELECT * FROM CUSTOMER;

CREATE TABLE ITEM(
    CODE NUMBER(4) PRIMARY KEY,
    INAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    REMAINS NUMBER(10)
);
SELECT * FROM ITEM;

CREATE TABLE BUYCUSTOMER(
    BCODE NUMBER(10) PRIMARY KEY,
    ID VARCHAR2(30) REFERENCES CUSTOMER(ID),
    BADDRESS VARCHAR2(100) UNIQUE NOT NULL,
    BTEL VARCHAR2(20) UNIQUE NOT NULL,
    BDATE DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM BUYCUSTOMER;

DROP SEQUENCE WISH_SEQ;
CREATE SEQUENCE WISH_SEQ
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE 
    NOCACHE;
    
CREATE TABLE WISHLIST(
    WNO NUMBER(2) PRIMARY KEY,
    ID VARCHAR2(30) REFERENCES CUSTOMER(ID),
    CODE NUMBER(4) REFERENCES ITEM(CODE),
    AMOUNT NUMBER(10),
    TOTAL NUMBER(20)
);
SELECT * FROM WISHLIST;

DROP SEQUENCE BUY_SEQ;
CREATE SEQUENCE BUY_SEQ
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE 
    NOCACHE;
    
CREATE TABLE BUYITEM(
    BUYNO NUMBER(2) PRIMARY KEY,
    CODE NUMBER(4) REFERENCES ITEM(CODE),
    BAMOUNT NUMBER(10),
    BTOTAL NUMBER(20)
);
SELECT * FROM BUYITEM;