DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);
SELECT * FROM CUS_LEVEL;

DROP SEQUENCE CUSTOMER_SEQ;
CREATE SEQUENCE CUSTOMER_SEQ
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE 
    NOCACHE;

CREATE TABLE CUSTOMER(
    CNO NUMBER(2) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(20) UNIQUE,
    POINT NUMBER(10),
    LEVELNO NUMBER(2) REFERENCES CUS_LEVEL(LEVELNO)
);
SELECT * FROM CUSTOMER;

INSERT INTO CUS_LEVEL VALUES (1,'VVIP');
INSERT INTO CUS_LEVEL VALUES (2,'VIP');
INSERT INTO CUS_LEVEL VALUES (3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4,'BLACK');

INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO) 
    VALUES (CUSTOMER_SEQ.NEXTVAL, 'È«±æµ¿', '17/10/17', '010-9999-9999', 300, 1);
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, LEVELNO) 
    VALUES (CUSTOMER_SEQ.NEXTVAL, 'ÀÌÃ¶¼ö', '16/09/06', '010-9999-9888', 2);
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO) 
    VALUES (CUSTOMER_SEQ.NEXTVAL, 'È«±æ¼ø', '16/09/07', '010-9999-7777', 50, 3);
    
DESC CUS_LEVEL;
DESC CUSTOMER;

SELECT CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNAME FROM CUS_LEVEL L, CUSTOMER C WHERE L.LEVELNO = C.LEVELNO;