SHOW USER;
SELECT * FROM DBA_TABLES;--ACCESS 불가 (DBA권한이 아님)
SELECT * FROM USER_TABLES;--내 계정이 가진 테이블
SELECT * FROM ALL_TABLES;--접근 가능한 테이블 정보
SELECT * FROM ALL_TABLES WHERE TABLE_NAME = 'EMP';
SELECT * FROM SCOTT.EMP;--ACCESS가능
EXIT;--접속해제
SELECT * FROM SCOTT.EMP; --권한 박탈
EXIT;
